import { User } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Josmar (Você)',
  email: 'josmar@email.com',
  phone: '(81) 99999-8888',
  cpf: '***.456.789-**',
  points: 1250,
  level: 'Sertanejo',
  totalSpent: 387.40,
  orderCount: 12,
  lgpdConsent: true,
  lgpdConsentDate: '2025-03-15',
  marketingConsent: true,
  segment: 'frequente',
  role: 'cliente',
  addresses: [
    {
      id: '1',
      label: 'Casa',
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apto 4',
      neighborhood: 'Boa Vista',
      city: 'Recife',
      state: 'PE',
      zipCode: '50050-000',
      isDefault: true,
    },
    {
      id: '2',
      label: 'Trabalho',
      street: 'Av. Boa Viagem',
      number: '456',
      neighborhood: 'Boa Viagem',
      city: 'Recife',
      state: 'PE',
      zipCode: '51020-000',
      isDefault: false,
    },
  ],
};

export const mockAtendente: User = {
  id: '2',
  name: 'João Souza',
  email: 'atendente@raizes.com',
  phone: '(81) 98888-7777',
  cpf: '***.654.321-**',
  points: 0,
  level: 'Caatingueiro',
  totalSpent: 0,
  orderCount: 0,
  lgpdConsent: true,
  lgpdConsentDate: '2025-01-10',
  marketingConsent: false,
  segment: undefined,
  role: 'atendente',
  storeId: 'rcf-01',
  addresses: [],
};

export const mockGerente: User = {
  id: '3',
  name: 'Ana Ferreira',
  email: 'gerente@raizes.com',
  phone: '(81) 97777-6666',
  cpf: '***.222.333-**',
  points: 0,
  level: 'Caatingueiro',
  totalSpent: 0,
  orderCount: 0,
  lgpdConsent: true,
  lgpdConsentDate: '2025-01-10',
  marketingConsent: false,
  segment: undefined,
  role: 'gerente',
  storeId: 'rcf-01',
  addresses: [],
};

export const mockAdmin: User = {
  id: '4',
  name: 'Carlos Administrador',
  email: 'admin@raizes.com',
  phone: '(81) 96666-5555',
  cpf: '***.666.777-**',
  points: 0,
  level: 'Caatingueiro',
  totalSpent: 0,
  orderCount: 0,
  lgpdConsent: true,
  lgpdConsentDate: '2025-01-10',
  marketingConsent: false,
  segment: undefined,
  role: 'admin',
  addresses: [],
};

export const MOCK_CREDENTIALS: Record<string, User> = {
  'josmar@email.com': mockUser,
  'atendente@raizes.com': mockAtendente,
  'gerente@raizes.com': mockGerente,
  'admin@raizes.com': mockAdmin,
};
